/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/d99kris/nchat/lib/wmchat/go */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 10 "cgowm.go"


 extern void WmNewContactsNotify(int p_ConnId, char* p_ChatId, char* p_Name, char* p_Phone, int p_IsSelf, int p_IsNotify);
 extern void WmNewChatsNotify(int p_ConnId, char* p_ChatId, int p_IsUnread, int p_IsMuted, int p_IsPinned, int p_LastMessageTime);
 extern void WmNewMessagesNotify(int p_ConnId, char* p_ChatId, char* p_MsgId, char* p_SenderId, char* p_Text, int p_FromMe, char* p_QuotedId, char* p_FileId, char* p_FilePath, int p_FileStatus, int p_TimeSent, int p_IsRead, int p_IsEditCaption);
 extern void WmNewStatusNotify(int p_ConnId, char* p_UserId, int p_IsOnline, int p_TimeSeen);
 extern void WmNewTypingNotify(int p_ConnId, char* p_ChatId, char* p_UserId, int p_IsTyping);
 extern void WmNewMessageStatusNotify(int p_ConnId, char* p_ChatId, char* p_MsgId, int p_IsRead);
 extern void WmNewMessageFileNotify(int p_ConnId, char* p_ChatId, char* p_MsgId, char* p_FilePath, int p_FileStatus, int p_Action);
 extern void WmNewMessageReactionNotify(int p_ConnId, char* p_ChatId, char* p_MsgId, char* p_SenderId, char* p_Text, int p_FromMe);
 extern void WmDeleteChatNotify(int p_ConnId, char* p_ChatId);
 extern void WmDeleteMessageNotify(int p_ConnId, char* p_ChatId, char* p_MsgId);
 extern void WmUpdateMuteNotify(int p_ConnId, char* p_ChatId, int p_IsMuted);
 extern void WmUpdatePinNotify(int p_ConnId, char* p_ChatId, int p_IsPinned, int p_TimePinned);
 extern void WmReinit(int p_ConnId);
 extern void WmSetProtocolUiControl(int p_ConnId, int p_IsTakeControl);
 extern void WmSetStatus(int p_ConnId, int p_Flags);
 extern void WmClearStatus(int p_ConnId, int p_Flags);
 extern int WmAppConfigGetNum(char* p_Param);
 extern void WmAppConfigSetNum(char* p_Param, int p_Value);
 extern void WmLogTrace(char* p_Filename, int p_LineNo, char* p_Message);
 extern void WmLogDebug(char* p_Filename, int p_LineNo, char* p_Message);
 extern void WmLogInfo(char* p_Filename, int p_LineNo, char* p_Message);
 extern void WmLogWarning(char* p_Filename, int p_LineNo, char* p_Message);
 extern void WmLogError(char* p_Filename, int p_LineNo, char* p_Message);

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern GoInt CWmInit(char* path, char* proxy, GoInt sendType);
extern GoInt CWmLogin(GoInt connId);
extern GoInt CWmLogout(GoInt connId);
extern GoInt CWmCleanup(GoInt connId);
extern GoInt CWmGetVersion();
extern GoInt CWmGetMessages(GoInt connId, char* chatId, GoInt limit, char* fromMsgId, GoInt owner);
extern GoInt CWmSendMessage(GoInt connId, char* chatId, char* text, char* quotedId, char* quotedText, char* quotedSender, char* filePath, char* fileType, char* editMsgId, GoInt editMsgSent);
extern GoInt CWmGetContacts(GoInt connId);
extern GoInt CWmGetStatus(GoInt connId, char* userId);
extern GoInt CWmMarkMessageRead(GoInt connId, char* chatId, char* senderId, char* msgId);
extern GoInt CWmDeleteMessage(GoInt connId, char* chatId, char* senderId, char* msgId);
extern GoInt CWmDeleteChat(GoInt connId, char* chatId);
extern GoInt CWmSendTyping(GoInt connId, char* chatId, GoInt isTyping);
extern GoInt CWmSendStatus(GoInt connId, GoInt isOnline);
extern GoInt CWmDownloadFile(GoInt connId, char* chatId, char* msgId, char* fileId, GoInt action);
extern GoInt CWmSendReaction(GoInt connId, char* chatId, char* senderId, char* msgId, char* emoji);

#ifdef __cplusplus
}
#endif
