#!/bin/sh /etc/rc.common

USE_PROCD=1
START=80
STOP=10

PROG=/usr/bin/main
CONF=/agent

start_service() {
        mkdir -p /agent/data/cloud
        mkdir -p /agent/data/snapshots
        mkdir -p /agent/data/log
        mkdir -p /agent/data/recordings
        mkdir -p /agent/data/capture-test
        mkdir -p /agent/data/config
        procd_open_instance
        procd_set_param command "$PROG" -config="$CONF" -action=run -port=7575
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}
