# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/lib/python3.10/dist-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /usr/local/lib/python3.10/dist-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/r/hdf5-2.0.0

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/r/hdf5-2.0.0/build

# Include any dependencies generated for this target.
include fortran/src/CMakeFiles/H5match_types.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include fortran/src/CMakeFiles/H5match_types.dir/compiler_depend.make

# Include the progress variables for this target.
include fortran/src/CMakeFiles/H5match_types.dir/progress.make

# Include the compile flags for this target's objects.
include fortran/src/CMakeFiles/H5match_types.dir/flags.make

fortran/src/CMakeFiles/H5match_types.dir/codegen:
.PHONY : fortran/src/CMakeFiles/H5match_types.dir/codegen

fortran/src/CMakeFiles/H5match_types.dir/H5match_types.c.o: fortran/src/CMakeFiles/H5match_types.dir/flags.make
fortran/src/CMakeFiles/H5match_types.dir/H5match_types.c.o: /root/r/hdf5-2.0.0/fortran/src/H5match_types.c
fortran/src/CMakeFiles/H5match_types.dir/H5match_types.c.o: fortran/src/CMakeFiles/H5match_types.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/root/r/hdf5-2.0.0/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object fortran/src/CMakeFiles/H5match_types.dir/H5match_types.c.o"
	cd /root/r/hdf5-2.0.0/build/fortran/src && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT fortran/src/CMakeFiles/H5match_types.dir/H5match_types.c.o -MF CMakeFiles/H5match_types.dir/H5match_types.c.o.d -o CMakeFiles/H5match_types.dir/H5match_types.c.o -c /root/r/hdf5-2.0.0/fortran/src/H5match_types.c

fortran/src/CMakeFiles/H5match_types.dir/H5match_types.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/H5match_types.dir/H5match_types.c.i"
	cd /root/r/hdf5-2.0.0/build/fortran/src && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /root/r/hdf5-2.0.0/fortran/src/H5match_types.c > CMakeFiles/H5match_types.dir/H5match_types.c.i

fortran/src/CMakeFiles/H5match_types.dir/H5match_types.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/H5match_types.dir/H5match_types.c.s"
	cd /root/r/hdf5-2.0.0/build/fortran/src && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /root/r/hdf5-2.0.0/fortran/src/H5match_types.c -o CMakeFiles/H5match_types.dir/H5match_types.c.s

# Object files for target H5match_types
H5match_types_OBJECTS = \
"CMakeFiles/H5match_types.dir/H5match_types.c.o"

# External object files for target H5match_types
H5match_types_EXTERNAL_OBJECTS =

bin/H5match_types: fortran/src/CMakeFiles/H5match_types.dir/H5match_types.c.o
bin/H5match_types: fortran/src/CMakeFiles/H5match_types.dir/build.make
bin/H5match_types: fortran/src/CMakeFiles/H5match_types.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --bold --progress-dir=/root/r/hdf5-2.0.0/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking C executable ../../bin/H5match_types"
	cd /root/r/hdf5-2.0.0/build/fortran/src && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/H5match_types.dir/link.txt --verbose=$(VERBOSE)
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --blue --bold "Generating the H5fortran_types.F90 and H5f90i_gen.h files"
	cd /root/r/hdf5-2.0.0/build/fortran && /root/r/hdf5-2.0.0/build/bin/H5match_types
	cd /root/r/hdf5-2.0.0/build/fortran/static && /usr/local/lib/python3.10/dist-packages/cmake/data/bin/cmake -E copy_if_different /root/r/hdf5-2.0.0/build/fortran/H5f90i_gen.h /root/r/hdf5-2.0.0/build/fortran/static/H5f90i_gen.h
	cd /root/r/hdf5-2.0.0/build/fortran/static && /usr/local/lib/python3.10/dist-packages/cmake/data/bin/cmake -E copy_if_different /root/r/hdf5-2.0.0/build/fortran/H5fortran_types.F90 /root/r/hdf5-2.0.0/build/fortran/static/H5fortran_types.F90
	cd /root/r/hdf5-2.0.0/build/fortran/shared && /usr/local/lib/python3.10/dist-packages/cmake/data/bin/cmake -E copy_if_different /root/r/hdf5-2.0.0/build/fortran/H5f90i_gen.h /root/r/hdf5-2.0.0/build/fortran/shared/H5f90i_gen.h
	cd /root/r/hdf5-2.0.0/build/fortran/shared && /usr/local/lib/python3.10/dist-packages/cmake/data/bin/cmake -E copy_if_different /root/r/hdf5-2.0.0/build/fortran/H5fortran_types.F90 /root/r/hdf5-2.0.0/build/fortran/shared/H5fortran_types.F90

# Rule to build all files generated by this target.
fortran/src/CMakeFiles/H5match_types.dir/build: bin/H5match_types
.PHONY : fortran/src/CMakeFiles/H5match_types.dir/build

fortran/src/CMakeFiles/H5match_types.dir/clean:
	cd /root/r/hdf5-2.0.0/build/fortran/src && $(CMAKE_COMMAND) -P CMakeFiles/H5match_types.dir/cmake_clean.cmake
.PHONY : fortran/src/CMakeFiles/H5match_types.dir/clean

fortran/src/CMakeFiles/H5match_types.dir/depend:
	cd /root/r/hdf5-2.0.0/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /root/r/hdf5-2.0.0 /root/r/hdf5-2.0.0/fortran/src /root/r/hdf5-2.0.0/build /root/r/hdf5-2.0.0/build/fortran/src /root/r/hdf5-2.0.0/build/fortran/src/CMakeFiles/H5match_types.dir/DependInfo.cmake "--color=$(COLOR)"
.PHONY : fortran/src/CMakeFiles/H5match_types.dir/depend

