#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10

PROG=/usr/bin/lightnvr
CONF=/etc/lightnvr/lightnvr.ini

start_service() {
        mkdir -p /var/lib/lightnvr/data
        mkdir -p /var/log/lightnvr
        mkdir -p /var/run/lightnvr
        mkdir -p /var/lib/lightnvr/data/recordings
        mkdir -p /var/lib/lightnvr/data/models
        mkdir -p /var/lib/lightnvr/data/database
        mkdir -p /var/lib/lightnvr/data/recordings/hls
        mkdir -p /var/lib/lightnvr/data/recordings/mp4
        procd_open_instance
        procd_set_param command "$PROG" -c "$CONF"
        procd_set_param limits core="unlimited"
        procd_set_param limits nofile="1000000 1000000"
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}
