#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90
STOP=10

PROG=/usr/bin/core

start_service() {
        mkdir -p /etc/restreamer
        mkdir -p /var/lib/restreamer
        mkdir -p /var/lib/restreamer/ui
        mkdir -p /var/lib/restreamer/data
        procd_open_instance
        procd_set_param env CORE_CONFIGFILE=/etc/restreamer/config.json CORE_DB_DIR=/etc/restreamer CORE_ROUTER_UI_PATH=/var/lib/restreamer/ui CORE_STORAGE_DISK_DIR=/var/lib/restreamer/data CORE_STORAGE_MIMETYPES_FILE=/var/lib/restreamer/mime.types
        procd_set_param command "$PROG"
        procd_set_param limits core="unlimited"
        procd_set_param limits nofile="1000000 1000000"
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}
