#!/bin/sh /etc/rc.common

USE_PROCD=1
START=88
STOP=10

start_service() {
        mkdir -p /opt/genieacs
        mkdir -p /opt/genieacs/ext
        mkdir -p /var/log/genieacs
        mkdir -p /etc/logrotate.d
        procd_open_instance
        procd_set_param env GENIEACS_FS_INTERFACE=0.0.0.0 GENIEACS_FS_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-fs-access.log GENIEACS_DEBUG_FILE=/var/log/genieacs/genieacs-debug.yaml NODE_OPTIONS=--enable-source-maps GENIEACS_EXT_DIR=/opt/genieacs/ext
        procd_set_param command "/usr/bin/genieacs-fs"
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}
