#!/bin/sh /etc/rc.common

USE_PROCD=1
START=88
STOP=10

start_service() {
        mkdir -p /opt/genieacs
        mkdir -p /opt/genieacs/ext
        mkdir -p /var/log/genieacs
        mkdir -p /etc/logrotate.d
        procd_open_instance
        procd_set_param command "/usr/bin/genieacs-nbi"
        procd_set_param file "/opt/genieacs/genieacs.env"
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}
