#!/bin/sh /etc/rc.common

USE_PROCD=1
START=98
STOP=10

PROG=/usr/bin/pm2

start_service() {
        procd_open_instance
        procd_set_param command "$PROG" start streamflow
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}

stop_service() {
        procd_open_instance
        procd_set_param command "$PROG" stop streamflow
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}
