#!/bin/sh /etc/rc.common

USE_PROCD=1
START=70
STOP=10

PROG=/usr/bin/mongod
CONF=/etc/mongodb/mongod.conf

start_service() {
        mkdir -p /var/lib/mongodb
        mkdir -p /var/log/mongodb
        procd_open_instance
        procd_set_param command "$PROG" --config "$CONF"
        procd_set_param limits core="unlimited"
        procd_set_param limits nofile="1000000 1000000"
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}
