#!/bin/sh /etc/rc.common

USE_PROCD=1
START=70
STOP=10

PROG=/usr/bin/mongod
CONF=/etc/mongodb/mongod.conf

start_service() {
        mkdir -p /var/lib/mongodb
        mkdir -p /var/log/mongodb
        procd_open_instance
        procd_set_param env MONGODB_CONFIG_OVERRIDE_NOFORK=1
        procd_set_param env GLIBC_TUNABLES=glibc.pthread.rseq=0
        procd_set_param command "$PROG" --config "$CONF"
        procd_set_param limits fsize="unlimited unlimited"
        procd_set_param limits cpu="unlimited unlimited"
        procd_set_param limits as="unlimited unlimited"
        procd_set_param limits nofile="64000 64000"
        procd_set_param limits rss="unlimited unlimited"
        procd_set_param limits nproc="64000 64000"
        procd_set_param limits memlock="unlimited unlimited"
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}
